### ISSUE TITLE
“空”本字以及含有“空”的字中的“空”字的字形需要美化吗？

### ISSUE THREAD

**Issue by cnstruggler** [GuiWonder/Shanggu#103]
含有“空”的字拿“腔”举例。![IMG_20241026_153622.jpg](https://github.com/user-attachments/assets/0647e8aa-b282-40df-b929-673417ae5316)

![IMG_20241026_153602.jpg](https://github.com/user-attachments/assets/4d52b1b4-c58e-468f-ab6a-456fa1443f60)

然而，《康熙字典》的字形为：![IMG_20241026_153746.jpg](https://github.com/user-attachments/assets/9005ece1-7005-4dc6-bee1-7f62c51617b4)

![IMG_20241026_153800.jpg](https://github.com/user-attachments/assets/e62af7ae-9d05-45d8-ab83-928c5c9df7b0)

旧书字体为：![IMG_20241026_153855.jpg](https://github.com/user-attachments/assets/c98c4362-7f18-4da8-86fc-0eb38bda0778)

![IMG_20241009_221032.jpg](https://github.com/user-attachments/assets/305d1f75-c382-407d-ba85-c8615b8b0d61)

**Comment by garfieldLSY** [comment]
回復樓主：
“穴”下方並非“八”，而是和寶蓋頭組合在一起形成洞穴的樣子，所以穴寶蓋下側作“撇、竪彎鈎”也没甚麽問題。
還有，有些字體帶變體選擇功能，其原理如該視頻鏈接所示。

https://b23.tv/aG35L84

簡單來説，衹要在想改變字形的字後面打選擇符，字形就會變。
以下爲選异選的鏈接，可以由此查看已編碼的變體：

https://747.codeberg.page/vsselector/#!/zh-hans/

*注：尚古系列目前僅支持Adobe-Japan1字集的變體選擇符

**Comment by cnstruggler** [comment]
行，了解。

**Comment by garfieldLSY** [comment]
注：“容”字的部首不是穴寶蓋。

**Comment by CingHok** [comment]
> 注：“容”字的部首不是穴寶蓋。

那是什么？

**Comment by garfieldLSY** [comment]
寶蓋頭。
