### ISSUE TITLE
黑体中车和专在非独体字中与作独体字显示时不同，如「转」

### ISSUE THREAD

**Issue by komatsugen** [GuiWonder/Shanggu#55]

**Comment by komatsugen** [comment]
另外还有「冬」，单独显示与在图，终等字里面时不同

**Comment by haydenwong7bm** [comment]
<img width="97" alt="image" src="https://github.com/GuiWonder/SourceHanToClassic/assets/51369959/33bc54d6-6d66-4b66-a1b3-08de2ddf6271">
