### ISSUE TITLE
「良」部件要修改吗？

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [GuiWonder/Shanggu#58]
传承字形当中，「良」部件首笔作长横，不作竖点和顿点。

**Comment by DevoteToStudy** [comment]
我覺得沒有必要，因爲《康熙字典》中的“良“字就是豎點。傳承字形寫法很多，我覺得沒有字理或美觀度上的原則性問題一般不用改。

**Comment by UltimateAmitieKaiNiC** [comment]
等一下

**Comment by UltimateAmitieKaiNiC** [comment]
原作者并没有注意到

**Comment by DevoteToStudy** [comment]
發生了甚麼事？

**Comment by UltimateAmitieKaiNiC** [comment]
> 發生了甚麼事？

有人说「良」部件不推荐修改

**Comment by DevoteToStudy** [comment]
> > 發生了甚麼事？
> 
> 有人说「良」部件不推荐修改

你是說我嗎？

**Comment by UltimateAmitieKaiNiC** [comment]
> > > 發生了甚麼事？
> > 
> > 
> > 有人说「良」部件不推荐修改
> 
> 你是說我嗎？

是啊

**Comment by UltimateAmitieKaiNiC** [comment]
> 我也覺得首筆為橫的「良」不太美觀，如圖。另外，二樓那貨做人不地道，別人和他觀點不同他就受不了了，不讓人講話。 ![sgs2532](https://private-user-images.githubusercontent.com/112676634/296417145-1771540e-ea61-4a54-bc02-f3ad0c4a158b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjA4MDIsIm5iZiI6MTcwNTEyMDUwMiwicGF0aCI6Ii8xMTI2NzY2MzQvMjk2NDE3MTQ1LTE3NzE1NDBlLWVhNjEtNGE1NC1iYzAyLWYzYWQwYzRhMTU4Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwNDM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzUyODQ3MDAwOTViOGRlZTYyMTdkZjk3YTUxMjM1YTQ1NmY2MjhlNTU4NmYzYjg2ZmFhNzgxMWI4MzkwY2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHHeaIZAUINCBG6eZCygGpxgHCba23xjZQb_WjIW_hs)

我也覺得，未來的一點源黑可能有所不同

**Comment by DevoteToStudy** [comment]
> 我也覺得首筆為橫的「良」不太美觀，如圖。另外，二樓那貨做人不地道，別人和他觀點不同他就受不了了，不讓人講話。 ![sgs2532](https://private-user-images.githubusercontent.com/112676634/296417145-1771540e-ea61-4a54-bc02-f3ad0c4a158b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjA4MDUsIm5iZiI6MTcwNTEyMDUwNSwicGF0aCI6Ii8xMTI2NzY2MzQvMjk2NDE3MTQ1LTE3NzE1NDBlLWVhNjEtNGE1NC1iYzAyLWYzYWQwYzRhMTU4Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwNDM1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmVmYTBkZDA3MTAyYzI0NTU2N2EwNzU0MzQ5YTk5MzliY2EwODU4ZGQ0MjUwNjg5ODMwMDY2ZjFmYWE1YTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHeXN72umCu5sgPL3AHlVJaXsPFeWxHN-xjhcE7JGoA)

灣灣覺靑你有證據嗎？

**Comment by DevoteToStudy** [comment]
而且我所說的「一般不用改」不是「最好別改」，注意甄別。

**Comment by UltimateAmitieKaiNiC** [comment]
> 而且我所說的「一般不用改」不是「最好別改」，注意甄別。

而且是主要美觀，跟未來的一點源黑有所不同

**Comment by DevoteToStudy** [comment]
> 我也覺得首筆為橫的「良」不太美觀，如圖。另外，二樓那貨做人不地道，別人和他觀點不同他就受不了了，不讓人講話。 ![sgs2532](https://private-user-images.githubusercontent.com/112676634/296417145-1771540e-ea61-4a54-bc02-f3ad0c4a158b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjA4ODcsIm5iZiI6MTcwNTEyMDU4NywicGF0aCI6Ii8xMTI2NzY2MzQvMjk2NDE3MTQ1LTE3NzE1NDBlLWVhNjEtNGE1NC1iYzAyLWYzYWQwYzRhMTU4Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwNDM2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWIzYzg0YTc0OTg2MDRjYmZlMzM1MjNhNWIwZGYxZWI0MDAxMDdmNjM3YzE1NTIzNTUzM2I0NjYyODRlNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G9zWcf0Eg4J5XmBaD1XYtjABsquVM70GBadEdng6aE4)

懶得跟你這臺蛙一般見識。

**Comment by DevoteToStudy** [comment]
> > 而且我所說的「一般不用改」不是「最好別改」，注意甄別。
> 
> 而且是主要美觀，跟未來的一點源黑有所不同

好，我只是發表我的意見，決定權不在於我。

**Comment by UltimateAmitieKaiNiC** [comment]
> > > 而且我所說的「一般不用改」不是「最好別改」，注意甄別。
> > 
> > 
> > 而且是主要美觀，跟未來的一點源黑有所不同
> 
> 好，我只是發表我的意見，決定權不在於我。

OK

**Comment by UltimateAmitieKaiNiC** [comment]
對了，那個Readme可以列出改或不改的部件的列表嗎？

**Comment by UltimateAmitieKaiNiC** [comment]
我明白了，“良”部件符合康熙字典字形。
