### ISSUE TITLE
茲／兹／玆之處理

### ISSUE THREAD

**Issue by SCLu17** [GuiWonder/Shanggu#69]
茲／兹／玆作傍時，建議可行情況下祇用茲或兹，不用玆。（茲正，兹俗，玆同音假借）
由於六地（陸港臺日韓朝）之間處理方式不同，字圖也會比較混亂，先槪括一下各地現行指引／標準：

- 大陸一律作兹，從䒑。
- 香港一律作茲，從艸。不過，由於「慈」有相容體，「磁」在B區有分開編碼，所以Unicode基本區內這兩個字是從兹的。碼表歸碼表，指引確實是從茲的。
- 臺灣單字用茲，作部件時則作兹。
- 日本單字收茲，作部件時，收於JIS內從兹（滋、孳、慈、磁、糍、鎡、鶿、鷀），螆爲例外，從玆。JIS外不拘，多數從茲。
- 韓國單字收玆。作部件時，鷀從茲；濨、甆從兹；鶿從玆，其餘與JIS同。思源KR版「滋」字從玆，疑爲錯編。
- 朝鮮除嗞、嵫、孶從玆外，其餘作部件時從兹。單字方面，朝鮮規格三字皆收，不過他們實際上會用哪個字，我就不知。

（按：茲、兹、玆、孶、孳為例外，Unicode沒有統一，故各地規格字形也不會統一。）

現時 (1.019) 從「茲」的字未作處理，但至少四個地區版本之中沒有分別，明黑體一樣。TC版因爲港臺有別，姑且不予置評。先在此假設「正常版」決定從艸，而 SC 與 JP 版從各地規格，那基本區要改從艸的就有：

- 滋 (6ECB) 建議用滋 (2F90B) 字形（Unicode規格從茲），不用滋 (FA99)（Unicode規格從玆）。SC、JP 除外，基本區應從䒑。
- 磁 (78C1) 可改從艸，與𥔵 (25535) 統一。SC、JP 除外。
- 禌 (798C) 可改從艸。SC、JP 除外。JP 雖然 JIS 不收，但Unicode碼表中亦從兹。
- 糍 (7CCD) 可改從艸。SC、JP 除外。
- 螆 (8786) 可改從艸。SC 除外，應改從䒑，見下。JP 除外，不改。
- 此外，孳 (5B73) 可改從䒑，見下。現時5B73從玆，爲5B76的朝鮮字形。

至於應改從䒑者有：
- 嗞 (55DE)，SC。
- 孳 (5B73)，所有版本。此字Unicode基本區不統一，有異體孶 (5B76)，該字則從茲。
- 嵫 (5D6B)，SC。
- 慈 (6148)，SC、JP。
- 滋 (6ECB)，SC、JP。
- 濨 (6FE8)，SC。
- 甆 (7506)，SC。
- 礠 (7920)，SC。
- 稵 (7A35)，SC。
- 螆 (8786)，SC。
- 鎡 (93A1)，SC。
- 鰦 (9C26)，SC。
- 鶿 (9DBF)，SC、JP。
- 鷀 (9DC0)，SC、JP。
- 此外，孶 (5B76) 所有版本宜維持分離。

當然也可以統一至別形，不過我覺得重要的是應作適當的統一。如果 SC 的原意是改「兹」作「茲」，那簡體（镃、鹚）也要下功夫了。
最優先是孳、滋兩字。謝謝！

**Comment by haydenwong7bm** [comment]
SC／JP版實爲多編碼漢字分開字圖，Unicode中已把「茲部件」和「兹部件」統一的字不應改從「兹」，SC／JP版原意是只把「茲」、「兹」、「玆」、「孶」、「孳」分開字圖，其他改「兹部件」作「茲部件」。
