### ISSUE TITLE
“碳”在黑體與宋體中并不統一

### ISSUE THREAD

**Issue by garfieldLSY** [GuiWonder/Shanggu#74]
![Screenshot_20240215_154155_ibisPaint X.png](https://github.com/GuiWonder/SourceHanToClassic/assets/95416906/ec125cd9-9a45-4175-9302-768cb7fb0047)

“碳”字在黑體和宋體中并不統一，建議另外檢查一下圓體并統一更改成“石山灰”或“石屵火”的字圖。

**Comment by 307587** [comment]
炭之傳承體是「⿱山⿸厂火」，厂非𠂇。
