### ISSUE TITLE
粗细掺杂

### ISSUE THREAD

**Issue by Bril87** [GuiWonder/Shanggu#89]
使用的RoundSC light 但好像掺杂了regular字重
![Screenshot_20240713_005857.jpg](https://github.com/user-attachments/assets/4c27efde-d6c2-4e8e-b0e8-0ffc7145c341)

“𠩄𬏟”

**Comment by GuiWonder** [comment]
RoundSC 不包含“𠩄𬏟”这两个字，这两个字可能使用了您系统上的字体。
